name: reviewdog
on: [pull_request]

jobs:
  QualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.22
          add_to_path: true

      - name: Detekt
        run: detekt-cli -i ${{ github.workspace }}
