name: reviewdog
on: [pull_request]

jobs:
  QualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.23.8
          add_to_path: true

      - name: List changed files
        uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          outputFormat: 'csv'

      - name: Detekt
        run: 
          detekt-cli -b baseline.xml -i ${{ steps.list-files.outputs.pullRequestFiles }} --report xml:detekt.xml

      - name: Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          path: detekt.xml
                golint ./... | reviewdog -f=golint -diff="git diff detekt"
          
         
