name: reviewdog
on: [pull_request]

jobs:
  QualityCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.22
          add_to_path: true

      - name: List changed files
        uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          outputFormat: 'csv'

      - name: Print changed files (debug)
        run: |
          for file in ${{ fromJson(steps.list-files.outputs.pullRequestFiles) }}; do
            echo "Changed Files - ${file}."
          done

      - name: Detekt
        run: |
          changed_files=$(echo ${{ fromJson(steps.list-files.outputs.pullRequestFiles) }} | tr ',' ' ')
          detekt-cli -i $changed_files